export type MemoryType =
  | 'note'
  | 'screenshot'
  | 'photo'
  | 'document'
  | 'link'
  | 'voice'
  | 'paste';

export type CategoryType =
  | 'Academic'
  | 'Personal'
  | 'Project'
  | 'Work'
  | 'Finance'
  | 'Ideas'
  | 'Reference'
  | 'Travel'
  | 'Shopping'
  | 'Health'
  | 'People'
  | 'Documents'
  | 'Other';

export type RelationshipType =
  | 'RELATED_TO'
  | 'MENTIONS'
  | 'SAME_TOPIC'
  | 'SAME_PROJECT'
  | 'SAME_PERSON'
  | 'SAME_EVENT'
  | 'BEFORE'
  | 'AFTER'
  | 'DERIVED_FROM'
  | 'REFERENCE_FOR';

export interface MemoryRelationship {
  targetMemoryId: string;
  relationshipType: RelationshipType;
  confidence: number;
  reason: string;
}

export interface Memory {
  id: string;
  userId?: string;
  title: string;
  content: string;
  summary: string;
  sourceType: MemoryType;
  category: CategoryType;
  topics: string[];
  entities: string[];
  keyFacts: string[];
  actionItems: string[];
  detectedDates: string[];
  sourceUrl?: string;
  imageUrl?: string;
  fileAttachment?: {
    name: string;
    size: number;
    mimeType: string;
  };
  relationships: MemoryRelationship[];
  importance: 'low' | 'normal' | 'high';
  isProcessing?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AIInsight {
  id: string;
  type: 'pattern' | 'deadline' | 'connection' | 'reflection';
  title: string;
  message: string;
  relatedMemoryIds: string[];
  createdAt: string;
}

export interface Collection {
  id: string;
  name: string;
  description: string;
  icon?: string;
  memoryCount: number;
  isAutoGenerated: boolean;
  memoryIds: string[];
}

export interface AskMemoryResponse {
  answer: string;
  storedFacts: string[];
  aiInterpretation: string;
  inference: string;
  confidenceScore: number;
  retrievedMemories: {
    id: string;
    title: string;
    snippet: string;
    sourceType: MemoryType;
    matchScore: number;
    relevanceReason: string;
  }[];
  insufficientInfo?: boolean;
}
